### ISSUE TITLE
Use simeple-file-manager in readOnly mode

### ISSUE THREAD

**Issue by Shirish-JavaDeveloper** [aws-solutions/simple-file-manager-for-amazon-efs#159]
**Is your feature request related to a problem? Please describe.**
- We want to see files that are stored onto **EFS** service. 
- I need to have a view where I can see list of files/directory present there. I should be able to download them(files/directory).
- I want to protect EFS from uploading new files by users using simple file manager. Nobody should be able toperform  _upload a new file_, _delete an existing file_ or _create new directory/ies_ .
- Currently I do not see a way to disable these options.
- It would be good if we intorduce the parameters to enable/disable the options (_**upload file / create new directory / delete file/ download file**_) 

**Describe the feature you'd like**
- Introduce a configuration parameter to disable the _upload file_ option
- Introduce a configuration parameter to disable the _delete file_ option
- Introduce a configuration parameter to disable the _create a directory_ option.
- Introduce a configuration parameter to disable the _download_ option.
- When user sets parameter value to false make sure that icon related to the functionality is hidden. 

**Additional context**
- An application logic is responsible to store files on EFS service.
- We just need a view(UI) to see/download the files present on efs server.

**Comment by brandold** [comment]
Hi @Shirish-JavaDeveloper, 

We will be adding additional permission schemes in the next release of the solution. I will go ahead and tag this feature request in the related issue for you to track.

**Comment by simonkrol** [comment]
Closing in lieu of #156 

Some updates on this task have been included on #174
