### ISSUE TITLE
"Unable to list filesystem objects. Check API logs "on click of Create Directory and Upload  file

### ISSUE THREAD

**Issue by kbhagi** [aws-solutions/simple-file-manager-for-amazon-efs#160]
**Describe the bug**

EFSMountConnectivityException found at the CW logs while listing the directories / files at the Simple File Manager UI. 

The root cause of this error was passing a VPC SecurityGroupId as the parameter at the CloudFormation stack  **-ManagedResources-fs-xxxxx** without ensuring that an inbound rule has an entry for NFS port 2049 at the SecurityGroup. There isn't an option provided at UI to specify a SecurityGroupId while onboarding a file system leading to picking a SecurityGroup without a NFS port.

Downside is that the SecurityGroups are hidden in the SimpleFileManager UI and they are sent as Request headers to an API https://xxxxxx.execute-api.us-east-1.amazonaws.com/api/filesystems/fs-xxxx/lambda

Without allowing access to NFS port 2049, Lambda function won't be able to connect to EFS mount point.

**To Reproduce**
1. Deployed the CloudFormation stack
2. Accessed the CloudFront Origin URL.
3. Logged in to the Simple File Manager UI using the credentials sent to my mail. 
4. Reset the password via the usual flow mentioned at the implementation
5. Found that no EFS files-systems were listed at the UI since they weren't any at my AWS region.
6. Created an EFS file-system via AWS EFS console UI. 
7. Refreshed the Simple File Manager UI to confirm if the file systems were listed. They got listed.
8. Clicked on false hyperlink to convert this EFS into a managed resource
9. A CFN stack  deployed the EFS access point and Lambda function
10. Checked the Route Tables of the subnets associated with EFS for any configuration.
11. Among the 4 subnets, only one had route to the NAT and other 3 had a local route (VPC CIDR as the destination and Target as local)
12. Refreshed the Simple File Manager CloudFront URL. The Managed was set to true at FileSystems
13. Accessed my file system by clicking on the File System Id
14. The console UI threw an error "Unable to list files" in a red banner
15. Clicking on creating a directory or uploading a file lead to the same error
16. Checked the CW log streams for the Lambda function EFSFileManagerAPI. Found the error EFSMountConnectivityException at the log.
17.  Checked the SecurityGroup associated with the Lambda function **fs-xxxxx-manager-lambda**. This did not have an entry for port 2049.

**Expected behavior**

- After converting an EFS file system to a managed resource, expected the listing of the files and directory instead of failing with **Unable to list files** or **EFSMountConnectivityException**. 
- A SecurityGroup Id has to be chosen that has an entry for NFS port 2049. This does not happen currently

**Please complete the following information about the solution:**
- [ v1.4.0] Version: [e.g. v1.0.4]

To get the version of the solution, you can look at the description of the created CloudFormation stack. If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode: 
    General: "solutions-reference"
      S3Bucket: "solutions"
      KeyPrefix: "simple-file-manager-for-amazon-efs/v1.4.0"
```

- [ us-east-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [no] If the answer to the previous question was yes, are the changes available on GitHub?
- [ yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ yes] Were there any errors in the CloudWatch Logs?

**Screenshots**
Two pictures with names **LambdaFunctionSecurityGroup.png** , **Unable-to-list-filesystemo-bjects.png** has been uploaded here

<img width="1405" alt="Unable-to-list-filesystemo-bjects" src="https://user-images.githubusercontent.com/19756773/136407460-517456ff-e6d6-4fe8-8cf9-4bb2ae4d8b4d.png">

<img width="1405" alt="LambdaFunctionSecurityGroup" src="https://user-images.githubusercontent.com/19756773/136407499-9e833d82-97de-43ac-b090-7c0de8eeb5e5.png">

**Additional context**
While this function **def create_filesystem_lambda():** gets interpreted  at line 339 of EFSFileManagerAPI function.  securityGroups list get extracted from the app variable. Found that SecurityGroups attached to EFS mount targets are captured and later the same security_groups are passed as in input into **create_manager_stack()** 

**fetching the Security Groups associated with an EFS mount target and returning the dictionary appended to a List netinfo**
```
response = EFS.describe_mount_target_security_groups(
                    MountTargetId=mount_target_id
                )
```

**Passing the security_groups list into a **def create_filesystem_lambda(filesystem_id):**

```
@app.route('/filesystems/{filesystem_id}/lambda', methods=['POST'], cors=True, \
    authorizer=AUTHORIZER)
def create_filesystem_lambda(filesystem_id):
    """
    Proxies the filesystem manager creation to the create_manager_stack
    helper function

    :param filesystem_id: The filesystem to create resources for
    :returns: Creation response
    :raises ChaliceViewError, BadRequestError
    """
    request = app.current_request
    json_body = request.json_body

    try:
        subnet_ids = json_body['subnetIds']
        security_groups = json_body['securityGroups']
        uid = json_body['uid']
        gid = json_body['gid']
        path = json_body['path']
    except KeyError as error:
        app.log.error(error)
        raise BadRequestError("Check API logs")

    try:
        response = create_manager_stack(filesystem_id, uid, gid, path, subnet_ids, security_groups)
    except Exception as error:
        app.log.error(error)
        app.log.debug('Failed to create stack, deleting it.')
        raise ChaliceViewError('Check API Logs')
    else:
        return response
        ```

**Comment by brandold** [comment]
Hi, @kbhagi 

Let me take a look at this over the next couple days. 

We're always happy to accept pull requests.
