### ISSUE TITLE
Other regions?

### ISSUE THREAD

**Issue by scaddenp** [aws-solutions/simple-file-manager-for-amazon-efs#164]
I only see US-east, US-west supported. Why not other regions? (eg ap-southeast)

**Comment by brandold** [comment]
Hi @scaddenp, those two regions are just the two regions that are provided from the Github page. The solution itself is supported in every region where all the solutions services are supported. You can find more information in the implementation guide here: https://docs.aws.amazon.com/solutions/latest/simple-file-manager-for-amazon-efs/design-considerations.html

We have customers using the solution in regions all over the world, so my recommendation would be to simply deploy it and test it out. 

Thanks!

**Comment by brandold** [comment]
Oh, and here is the link to the solutions webpage to deploy it: https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs/

Click the link titled "Launch in the AWS Console". Then adjust your region in the console accordingly.

**Comment by scaddenp** [comment]
Fantastic. Thanks for that.
