### ISSUE TITLE
Reduce abilities of Amazon Cognito Usere

### ISSUE THREAD

**Issue by bryan092785** [aws-solutions/simple-file-manager-for-amazon-efs#174]
I would like to have all users that I create in the Amazon Cognito module for this project only have the view and download permissions. I am sure this is possible through IAM Roles but am not 100% sure. 

With very little development and coding experience, I am hoping I can get some direction on making this possible. Thank you for this project as it can suit my very specific need rather fully when I figure out how to create groups with restricted permissions.

**Comment by brandold** [comment]
Hi @bryan092785, this is a feature request we're working on right now. There's a fair amount of internal processes we need to go through before releasing, but we're aiming to have this functionality available in the next version.

**Comment by CorgioluAtElipse** [comment]
Any news on live release

**Comment by simonkrol** [comment]
Hi @CorgioluAtElipse, we're still working through the internal processes for release. Development for this feature has mostly been completed and we expect to have this feature included in the v1.6.0 release.

@bryan092785 If you are interested in making this happen yourself for a customized version of the Solution, you can do so by:
- Modify `efs-file-manager-auth.yaml` to include a new `AWS::Cognito::UserPoolGroup` with your desired group name
- In the same file, create a new `AWS::IAM::ROLE` to attach to this user pool group.
  - The policy document for this role can use the following resource to allow it only to hit GET endpoints for the API:
    - "Resource": ["arn:aws:execute-api:${region}:${account}:${api}/*/GET/*"]
- After deployment, create a new Cognito user from the AWS console, and attach the new group to the user.

This will permit you to have a user which when logged in will only be able to view and download files. Keep in mind that the frontend will still show the buttons to perform those actions.

**Comment by CorgioluAtElipse** [comment]
Thank you for your response.
I had already implemented your solution with custom user group
But actually i need to be able to manage the access policies based on the path parameter passed to the api.
I think this is possibile only adding a lambda authorizer that create policies based on this parameter.

Thank you for your time
