### ISSUE TITLE
The following resource(s) failed to   create: [RestAPI].

### ISSUE THREAD

**Issue by SamuelLarkin** [aws-solutions/simple-file-manager-for-amazon-efs#186]
**Describe the bug**
I'm trying to launch a [Simple File Manager for Amazon EFS](https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs/) but it fails with 
`EFSFileManagerAPI`
```
Embedded stack arn:aws:cloudformation:ca-central-1:IDIDIDIDIDID:stack/EFSAccessor-EFSFileManagerAPI-
  1W4QUA1DG6MRC/XXXXXXXX-6c41-11ed-9c09-0e965e613246 was not successfully created: The following resource(s) failed to
  create: [RestAPI].
```

**To Reproduce**
* Navigate to [Simple File Manager for Amazon EFS](https://aws.amazon.com/solutions/implementations/simple-file-manager-for-amazon-efs/)
* Click `Launch in the AWS Console`
* Enter a `Stack Name`
* Enter an `AdminEmail`
* Then click `Next`
* Accept:
    * I acknowledge that AWS CloudFormation might create IAM resources with custom names.
    * I acknowledge that AWS CloudFormation might require the following capability: CAPABILITY_AUTO_EXPAND
* Click `Submit`
* Look at your `CloudFormation` / `Stack Detail` / `Events` for the error message under `EFSFileManagerAPI`

**Expected behavior**
I expect the stack to deploy completely without error.

**Please complete the following information about the solution:**
- v1.5.0

- [ca-central-1 ]
- [No] Was the solution modified from the version published on this repository?
- [N/A] If the answer to the previous question was yes, are the changes available on GitHub?
- [No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by SamuelLarkin** [comment]
I accidentally managed to briefly catch a glance of an intermediate substack that had the following error.

`RestAPI`
```
User: arn:aws:iam::IDIDIDIDIDID:user/ME is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:ca-central-1::/restapis because no iden    tity-based policy allows the apigateway:POST action (Service: AmazonApiGateway; Status Code: 403; Error Code: AccessDeniedException; Request ID: ab2a8d19-8b5f-433    4-a291-b4802a75f519; Proxy: null)
```

**Comment by simonkrol** [comment]
Hi @SamuelLarkin, thanks for your patience here.

In order to deploy the RestAPI included as part of the Simple File Manager CloudFormation template, you are required to have the apigateway:POST permission, please check to ensure that your user has that permission.

Please either open a new issue or respond here if you continue to run into problems.

Thanks,
Simon
