### ISSUE TITLE
No mount targets available

### ISSUE THREAD

**Issue by marcmmx** [aws-solutions/simple-file-manager-for-amazon-efs#187]
After logging into File manager it says no mount targets available for the filesystem. 
But I have 3 mount targets available across 3 subnets. 
I tried the deployment several times, but same message everytime and no submit button.

**Comment by simonkrol** [comment]
Hi @marcmmx, thanks for your patience here, can you provide some additional information about this issue (if you're still having it)?

- [ ] What region did you deploy in: [e.g. us-east-1]
- [ ] What version of the solution were you using: [e.g. v1.5.2]
- [ ] Did you deploy directly from the solutions library or did you deploy the template that exists here?
- [ ] If the answer to the previous question was that you used the Github template, was it a clean template or one you customized?
- [ ] Please describe the steps you'd take to reproduce this issue:

**Comment by lisenet** [comment]
Identical problem here.

I was following these instructions:

https://docs.aws.amazon.com/solutions/latest/simple-file-manager-for-amazon-efs/automated-deployment.html

* AWS region: eu-west-2 (London)
* (SO0145) Simple File Manager for Amazon EFS Solution Main v1.5.2

Deployed directly from the solutions library (link below) with no changes.

https://solutions-reference.s3.amazonaws.com/simple-file-manager-for-amazon-efs/latest/simple-file-manager-for-amazon-efs.template

When I log into the Simple File Manager WebUI, and attempt to create file manager lambda, I get this:

```
No mount targets available for the filesystem with security group(s) configured for NFS access. See the deployment guide for further details.
```

**Comment by lisenet** [comment]
Resolved.

> The solution also requires that the security group associated with the file system you are attempting to manage has permissible ingress and egress rules for allowing NFS traffic to the solutions File Manager Lambda function. The solution will prevent you from creating a manager function if it does not detect correct rules in place.

Lambda wanted an ingress rule for NFS protocol to access EFS, although it does not seem to be documented where Lambda will be accessing EFS from.

**Comment by Ahmad-anility** [comment]
Does anyone know how to define the ingress rule to fix this issue?

**Comment by lisenet** [comment]
@Ahmad-anility use a security group that's attached to your EFS.

**Comment by gsingh04** [comment]
I was able to replicate the behavior and can confirm the fix is adding inbound rule to allow NFS traffic on EFS mount targets, as highlighted by @lisenet. We will add the missing detail in our implementation guide. I will close this thread, please feel free to reach out should you have more questions.

**Comment by anthony-keller** [comment]
Normally what I'd do in this situation is creating an ingress rule on the security group of the EFS volume to allow `NFS` to the security group of the Lambda function. In this case, the `EFSFileManagerAPI` is not created in a VPC so doesn't have a security group.

What is the most secure way to allow access? Is a rule allowing `0.0.0.0/0` on port `2049` secure given the EFS volume exists in the restricted subnets?
