### ISSUE TITLE
Initial login not possible

### ISSUE THREAD

**Issue by bavarianbytes** [aws-solutions/simple-file-manager-for-amazon-efs#190]
**Describe the bug**
After creating the stack, visiting the `EFSFileSimpleWebsiteUrl` website doesn't show any login possibility. The JavaScript console throws: `Uncaught (in promise) No current user`

**To Reproduce**
1) Launch the CloudFormation stack from this website: https://docs.aws.amazon.com/de_de/solutions/latest/simple-file-manager-for-amazon-efs/automated-deployment.html#step-1.-launch-the-stack
2) Switch the AZ to eu-central-1
3) Enter a name, run, wait for finishing
4) Visit `EFSFileSimpleWebsiteUrl` website

**Expected behavior**
A login box to appear on the `EFSFileSimpleWebsiteUrl` website

**Please complete the following information about the solution:**
- [x] Version: **v1.5.0**
- [x] Region: **eu-central-1**
- [x] Was the solution modified from the version published on this repository? **NO**
- [x] If the answer to the previous question was yes, are the changes available on GitHub? **n/a**
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? **YES, no quotas reached**
- [x] Were there any errors in the CloudWatch Logs? **NO**

**Screenshots**
<img width="1653" alt="Bildschirm­foto 2023-02-10 um 14 48 41" src="https://user-images.githubusercontent.com/17915115/218107808-114bc1f9-83a9-4f5c-a80a-a810357d6927.png">

**Additional context**
n/a

**Comment by simonkrol** [comment]
Hi @bavarianbytes, this is a known bug caused by an update to the `aws-amplify-vue` package. We should have a fix out in the next release of the Simple File Manager for Amazon EFS. In the meantime, you can follow these steps to workaround the issue:
1. Modify the version of the `aws-amplify-vue` package in `source/web/package.json` from `^2.1.5` to `2.1.5`
2. Delete `source/web/package-lock.json` and `source/web/node_modules`.
3. Rebuild the project using `build-s3-dist.sh`
4. Deploy a new CloudFormation stack from the newly generated template

**Comment by bavarianbytes** [comment]
Thx. Tried it, didn't work, too much unknown stuff for me.

Is there a CloudFormation template of the 1.3.0-beta available somewhere i can use? Similar to this URL: https://solutions-reference.s3.amazonaws.com/simple-file-manager-for-amazon-efs/latest/simple-file-manager-for-amazon-efs.template

**Comment by simonkrol** [comment]
I'm not certain what you mean by the `1.3.0-beta`, but the templates for all released versions of the Solution (`v1.4.0`, `v1.4.1` and `v1.5.0`) should all be accessible using the link you provided by replacing `latest` with the version name. For example: https://solutions-reference.s3.amazonaws.com/simple-file-manager-for-amazon-efs/v1.4.1/simple-file-manager-for-amazon-efs.template would allow you to deploy v1.4.1.

For the workaround I provided, did you run into the same issue with the login page not appearing?

**Comment by bavarianbytes** [comment]
> I'm not certain what you mean by the `1.3.0-beta`
I had a look on the [release page](https://github.com/aws-solutions/simple-file-manager-for-amazon-efs/releases).

> but the templates for all released versions of the Solution (`v1.4.0`, `v1.4.1` and `v1.5.0`) should all be accessible using the link you provided by replacing `latest` with the version name. For example: https://solutions-reference.s3.amazonaws.com/simple-file-manager-for-amazon-efs/v1.4.1/simple-file-manager-for-amazon-efs.template would allow you to deploy v1.4.1.
Perfect, thank you. 1.4.1 works for me.

> For the workaround I provided, did you run into the same issue with the login page not appearing?
No, i managed to install python and the npm deps. Created S3 buckets. But had some errors when i tried to build the CloudFormation template with `build-s3-dist.sh`.
