### ISSUE TITLE
Document size limits

### ISSUE THREAD

**Issue by CGarces** [aws-solutions/simple-file-manager-for-amazon-efs#205]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this solution has a size limitation.
Api Gategay has a limit of 10GB in the response.

**Describe the feature you'd like**
If the size limit is a constrain should be documented in the readme.

**Additional context**

I'm not sure if is possible to use the  Lambda response streaming to bypass this limitation

**Comment by simonkrol** [comment]
Hi @CGarces, 
While API Gateway does have a 10MB response limit, lambda streaming would only get us up to 20MB. We instead overcome this for larger files by implementing the streaming ourself in the API Lambda. Files are uploaded and downloaded in chunks smaller than the 10MB ApiGateway and 6MB Lamabda response limits, with the frontend sending new requests for each chunk.

Let me know if you have any other questions.
Simon
