### ISSUE TITLE
Is it possible to give access to other users?

### ISSUE THREAD

**Issue by luiztauffer** [aws-solutions/simple-file-manager-for-amazon-efs#207]
I would like to give access to the web UI to other users, is that possible to do?

**Comment by simonkrol** [comment]
Hi @luiztauffer, 
Yes you can create new Cognito users through the AWS console. There should be a user pool created when you deployed, called SimpleFileManagerUserPool-(SomeID). Keep in mind that when you create the user, you'll need to add them to the administrator group in order for them to be able to access files.

Let me know if you have any other questions,
Simon
