### ISSUE TITLE
Update APIHandler Lambda function to latest version of Python

### ISSUE THREAD

**Issue by josh383451** [aws-solutions/simple-file-manager-for-amazon-efs#219]
**Is your feature request related to a problem? Please describe.**
AWS have announced Python 3.8 will not be supported as of October 14th.

**Describe the feature you'd like**
The APIHandler lambda function should use Python 3.11 (Latest version).

**Comment by simonkrol** [comment]
Hi @josh383451,

This change will be included alongside the next release of Simple File Manager.

Thanks for your contribution :) 
Simon

**Comment by simonkrol** [comment]
Change has been included as part of v1.5.7. Thank you :)
