### ISSUE TITLE
If a filesystem's stack changes from CREATE_COMPLETE to UPDATE_COMPLETE it no longer lists as managed

### ISSUE THREAD

**Issue by karmseveeratjisc** [aws-solutions/simple-file-manager-for-amazon-efs#229]
**Describe the bug**
If a filesystem's stack changes from CREATE_COMPLETE to UPDATE_COMPLETE it no longer lists as managed (and you can't do anything with it)

The code here only allows for CREATE_COMPLETE:
https://github.com/aws-solutions/simple-file-manager-for-amazon-efs/blob/main/source/api/app.py#L104

**To Reproduce**
Update a filesystem's stack (it appears simply adding tags can do this)

**Expected behavior**
The filesystem remains as managed=true even if the stack is updated

**Please complete the following information about the solution:**
- [v1.5.8 ] Version: [e.g. v1.0.4]

- [eu-west-1 ] Region: [e.g. us-east-1]
- [ no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ no] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ no] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://github.com/user-attachments/assets/eac3495d-069a-46f0-9a05-5bb8b6c0c1d3)

**Comment by simonkrol** [comment]
Hi @karmseveeratjisc,

Thanks for the report, I'll make sure we go ahead and fix that in the next release.

Simon
