### ISSUE TITLE
SM - Chalice x-ray support research. See if Chalice support AWS XRay. 

### ISSUE THREAD

**Issue by eggoynes** [aws-solutions/simple-file-manager-for-amazon-efs#86]

**Comment by eggoynes** [comment]
Found this issue on GitHub where people are asking for X-ray support in Chalice. 
https://github.com/aws/chalice/issues/464

**Comment by eggoynes** [comment]
Reading through the PR to add support it looks like I can just add this to the config.json for Chalice. 
https://github.com/aws/chalice/pull/1159/commits/922fb57a81194a77b2df564f4f4e822ca082505d

Here it is in the documentation. 
https://aws.github.io/chalice/topics/configfile.html?highlight=xray

**Comment by dreamorosi** [comment]
So I added the `xray` key to the Chalice config file like this:
```json
"dev": {
      "manage_iam_role": false,
      "iam_role_arn": "arn:aws:iam::999999999999:role/DummyRoleToBeReplaced",
      "api_gateway_stage": "api",
      "xray": true
    }
```
and the output Cfn template had `Tracing` enabled only in the `AWS::Serverless::Function` resource but not in the `AWS::Serverless::Api` one, which I think is what we need. I have [opened an issue](https://github.com/aws/chalice/issues/1753) in the Chalice repo about this.

Based on the SAM spec it seems that the `AWS::Serverless::Api` resource actually specifies two properties [`AccessLogSetting`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-accesslogsetting) and [`TracingEnabled`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-tracingenabled) but by looking at the Chalice docs + codebase they don't seem to be implemented (I could find that tracing is implemented only for functions resources i.e. [here](https://github.com/aws/chalice/blob/master/chalice/package.py#L247), [here](https://github.com/aws/chalice/blob/master/chalice/awsclient.py#L396), [here](https://github.com/aws/chalice/blob/master/chalice/awsclient.py#L1132)).

A quick, and hacky, way to add these two parameters would be to bypass Chalice and add these properties to the generated template while running the deployment `build-s3-dist.sh` script [at some point here](https://github.com/aws-samples/aws-efs-simple-file-manager/blob/development/deployment/build-s3-dist.sh#L272).

Aside from not being very elegant, the issue I see with this is that in order for access logging to actually work another resource of type [`AWS::ApiGateway::Account`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html) must be deployed.

**Comment by brandold** [comment]
Have you looked at the [external resource file](https://github.com/aws-samples/aws-efs-simple-file-manager/blob/development/source/api/external_resources.json)? This file allows you to manually adjust the auto generated chalice template, which could address the issues you described above.

**Comment by dreamorosi** [comment]
Right on the money; I'm not super familiar with Chalice so I didn't know that the file you mentioned allows to extend the generated Cfn template; was able to implement everything and I'm gonna send a PR.

**Comment by brandold** [comment]
Related issue #87
